namespace Emmy.Data.Enums
{
    public enum Image : byte
    {
        Placeholder = 0,
        ShopBanner = 1,
        ShopRole = 2,
        Vendor = 3,
        ShopSeed = 4,
        UserInventory = 5,
        Fishing = 6,
        Harvesting = 7,
        NotExpectedException = 8,
        ExpectedException = 9,
        UserRoles = 10,
        UserBanners = 11,
        GetGameRoles = 12,
        Welcome = 13,
        WelcomeScheduledEvents = 14,
        WelcomeGameWorld = 15,
        WelcomeVoiceChannels = 16,
        RequestGenderRole = 17,
        ShopKey = 18,
        Wardrobe = 19,
        UserTitles = 20,
        WorldInfo = 21,
        UserCollection = 22,
        UserAchievements = 23,
        Transit = 24,
        DailyReward = 25,
        Contract = 26,
        Casino = 27,
        DailyRide = 28,
        Relationship = 29,
        PrivateRoom = 30,
        Container = 31,
        GetPremium = 32,
        PremiumInfoRole = 33,
        PremiumInfoWardrobe = 34,
        PremiumInfoCommandColor = 35,
        Rating = 36,
        DonateInfo = 37,
        DailyRewardPremium = 38,
        Referral = 39,
        ReferralRewards = 40
    }
}