namespace Emmy.Data.Enums
{
    public enum WorldProperty : byte
    {
        EconomyStartupCapital = 1,
        TransferCurrencyTaxPercentWithoutPremium = 2,
        TransferCurrencyTaxPercentWithPremium = 3,
        PremiumPrice30days = 4,
        PremiumPrice365days = 5,
        PremiumFullPrice365days = 6,
        CasinoBetCooldownDurationInMinutes = 7,
        FishRarityChanceCommon = 8,
        FishRarityChanceRare = 9,
        FishRarityChanceEpic = 10,
        FishRarityChanceMythical = 11,
        FishRarityChanceLegendary = 12,
        FishFailChanceCommon = 13,
        FishFailChanceRare = 14,
        FishFailChanceEpic = 15,
        FishFailChanceMythical = 16,
        FishFailChanceLegendary = 17,
        FishingDefaultDurationInMinutes = 18,
        XpFishing = 19,
        DailyRewardMondayAmountWithoutPremium = 20,
        DailyRewardMondayAmountPremium = 21,
        DailyRewardTuesdayAmountWithoutPremium = 22,
        DailyRewardTuesdayAmountPremium = 23,
        DailyRewardWednesdayAmountWithoutPremium = 24,
        DailyRewardWednesdayAmountPremium = 25,
        DailyRewardThursdayAmountWithoutPremium = 26,
        DailyRewardThursdayAmountPremium = 27,
        DailyRewardFridayAmountWithoutPremium = 28,
        DailyRewardFridayAmountPremium = 29,
        DailyRewardSaturdayAmountWithoutPremium = 30,
        DailyRewardSaturdayAmountPremium = 31,
        DailyRewardSundayAmountWithoutPremium = 32,
        DailyRewardSundayAmountPremium = 33,
        DailyRewardBonusAmountWithoutPremium = 34,
        DailyRewardBonusAmountPremium = 35
    }
}