namespace Emmy.Data.Enums
{
    public enum WorldProperty : byte
    {
        EconomyStartupCapital = 1,
        TransferCurrencyTaxPercentWithoutPremium = 2,
        TransferCurrencyTaxPercentWithPremium = 3,
        PremiumPrice30days = 4,
        PremiumPrice365days = 5,
        PremiumFullPrice365days = 6,
        CasinoBetCooldownDurationInMinutes = 7,
        FishingDefaultDurationInMinutes = 18,
        XpFishing = 19,
        DailyRewardMondayAmountWithoutPremium = 20,
        DailyRewardMondayAmountPremium = 21,
        DailyRewardTuesdayAmountWithoutPremium = 22,
        DailyRewardTuesdayAmountPremium = 23,
        DailyRewardWednesdayAmountWithoutPremium = 24,
        DailyRewardWednesdayAmountPremium = 25,
        DailyRewardThursdayAmountWithoutPremium = 26,
        DailyRewardThursdayAmountPremium = 27,
        DailyRewardFridayAmountWithoutPremium = 28,
        DailyRewardFridayAmountPremium = 29,
        DailyRewardSaturdayAmountWithoutPremium = 30,
        DailyRewardSaturdayAmountPremium = 31,
        DailyRewardSundayAmountWithoutPremium = 32,
        DailyRewardSundayAmountPremium = 33,
        DailyRewardBonusAmountWithoutPremium = 34,
        DailyRewardBonusAmountPremium = 35,
        FractionAllowableCountAdvantage = 36,
        FractionGiftPrice = 37,
        FractionGiftCooldownDurationInHours = 38,
        FractionRaidCooldownDurationInHours = 39,
        ContainerTokenMinAmount = 40,
        ContainerTokenMaxAmount = 41,
        FarmPrice = 42,
        FarmExpansionL1Price = 43,
        FarmExpansionL2Price = 44,
        FarmWateringTime = 45,
        XpCropHarvesting = 46,
        RenameCooldownDurationInHours = 47,
        XpFarmWatering = 48,
        XpFractionGift = 49,
        XpFractionRaid = 50
    }
}